---
ansible_user: {% raw %}"{{ lookup('ansible.builtin.env', 'CVUSER', default='cvaas') }}"{% endraw %}
# CV_API_TOKEN must be generated in advance, valid and set as env variable
ansible_password: {% raw %}"{{ lookup('ansible.builtin.env', 'CV_API_TOKEN') }}"{% endraw %}
ansible_connection: httpapi
ansible_network_os: eos
ansible_httpapi_use_ssl: True
ansible_httpapi_validate_certs: True
ansible_httpapi_port: 443
