---
all:
  children:

    CV_SERVERS:
      hosts:
        lab_cv_instance:
          ansible_host: {% raw %}"{{ lookup('ansible.builtin.env', 'CVURL', default='www.cv-staging-corp.arista.io') }}"{% endraw %}

    {{ cookiecutter.in.avd.fabric_name }}:
      children:

        {{ cookiecutter.in.avd.fabric_name }}_SPINES:
          vars:
            type: spine
          hosts:
{%- for spine in cookiecutter.in.fabric_spine_inventory %}
            {{ spine.hostname }}:
              ansible_host: {{ spine.management_ip.split('/')[0] }}
{%- endfor %}

        {{ cookiecutter.in.avd.fabric_name }}_LEAFS:
          vars:
            type: l3leaf
          children:
{%- for leaf in cookiecutter.in.fabric_leaf_inventory %}
  {%- set leaf_id_int = leaf.id | int %}
  {%- if leaf_id_int % 2 != 0 %}
            pod{{ leaf_id_int // 2 }}:
              hosts:
  {%- endif %}
                {{ leaf.hostname }}:
                  ansible_host: {{ leaf.management_ip.split('/')[0] }}
{%- endfor %}

        {{ cookiecutter.in.avd.fabric_name }}_L2LEAFS:
          vars:
            type: l2leaf
          hosts:
{%- for leaf in cookiecutter.in.fabric_l2leaf_inventory %}
            {{ leaf.hostname }}:
              ansible_host: {{ leaf.management_ip.split('/')[0] }}
{%- endfor %}

    {{ cookiecutter.in.avd.fabric_name }}_ENDPOINTS:
      children:
        {{ cookiecutter.in.avd.fabric_name }}_LEAFS:

    {{ cookiecutter.in.avd.fabric_name }}_TENANTS:
      children:
        {{ cookiecutter.in.avd.fabric_name }}_LEAFS:
