---
fabric_name: AVD_FABRIC

# Set default uplink, downlink, and MLAG interfaces based on node type
default_interfaces:
  # - types: [ spine ]
  #   platforms: [ default ]
  #   uplink_interfaces: [ Ethernet1-2 ]
  #   downlink_interfaces: [ Ethernet1-8 ]
  - types: [ l3leaf ]
    platforms: [ default ]
    # uplink_interfaces: [ Ethernet1-2 ]
    # mlag_interfaces: [ Ethernet3-4 ]
    downlink_interfaces: [ Ethernet11-12 ]
  - types: [ l2leaf ]
    platforms: [ default ]
    uplink_interfaces: [ Ethernet11-12 ]

# Spine Switches
spine:
  defaults:
    platform: cEOS
    bgp_as: 65100
    loopback_ipv4_pool: 192.0.255.0/24
  nodes:
    - name: S01
      id: 1
      mgmt_ip: 192.168.0.11/24
    - name: S02
      id: 2
      mgmt_ip: 192.168.0.12/24
    - name: S03
      id: 3
      mgmt_ip: 192.168.0.13/24
    - name: S04
      id: 4
      mgmt_ip: 192.168.0.14/24

l3leaf:
  defaults:
    platform: cEOS
    loopback_ipv4_pool: 192.0.254.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 192.0.253.0/24
    uplink_interfaces: ['Ethernet21', 'Ethernet22', 'Ethernet23', 'Ethernet24']
    uplink_switches: ['S01', 'S02', 'S03', 'S04']
    uplink_ipv4_pool: 172.30.255.0/24
    mlag_interfaces: ['Ethernet31', 'Ethernet32']
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
    virtual_router_mac_address: 00:1c:73:00:dc:01
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
  node_groups:
    - group: pod0
      bgp_as: 65101
      nodes:
        - name: L01
          id: 1
          mgmt_ip: 192.168.0.101/24
          uplink_switch_interfaces: ['Ethernet1', 'Ethernet1', 'Ethernet1', 'Ethernet1']
        - name: L02
          id: 2
          mgmt_ip: 192.168.0.102/24
          uplink_switch_interfaces: ['Ethernet2', 'Ethernet2', 'Ethernet2', 'Ethernet2']
    - group: pod1
      bgp_as: 65102
      nodes:
        - name: L03
          id: 3
          mgmt_ip: 192.168.0.103/24
          uplink_switch_interfaces: ['Ethernet3', 'Ethernet3', 'Ethernet3', 'Ethernet3']
        - name: L04
          id: 4
          mgmt_ip: 192.168.0.104/24
          uplink_switch_interfaces: ['Ethernet4', 'Ethernet4', 'Ethernet4', 'Ethernet4']
    - group: pod2
      bgp_as: 65103
      nodes:
        - name: L05
          id: 5
          mgmt_ip: 192.168.0.105/24
          uplink_switch_interfaces: ['Ethernet5', 'Ethernet5', 'Ethernet5', 'Ethernet5']
        - name: L06
          id: 6
          mgmt_ip: 192.168.0.106/24
          uplink_switch_interfaces: ['Ethernet6', 'Ethernet6', 'Ethernet6', 'Ethernet6']
    - group: pod3
      bgp_as: 65104
      nodes:
        - name: L07
          id: 7
          mgmt_ip: 192.168.0.107/24
          uplink_switch_interfaces: ['Ethernet7', 'Ethernet7', 'Ethernet7', 'Ethernet7']
        - name: L08
          id: 8
          mgmt_ip: 192.168.0.108/24
          uplink_switch_interfaces: ['Ethernet8', 'Ethernet8', 'Ethernet8', 'Ethernet8']
    - group: pod4
      bgp_as: 65105
      nodes:
        - name: L09
          id: 9
          mgmt_ip: 192.168.0.109/24
          uplink_switch_interfaces: ['Ethernet9', 'Ethernet9', 'Ethernet9', 'Ethernet9']
        - name: L10
          id: 10
          mgmt_ip: 192.168.0.110/24
          uplink_switch_interfaces: ['Ethernet10', 'Ethernet10', 'Ethernet10', 'Ethernet10']
    - group: pod5
      bgp_as: 65106
      nodes:
        - name: L11
          id: 11
          mgmt_ip: 192.168.0.111/24
          uplink_switch_interfaces: ['Ethernet11', 'Ethernet11', 'Ethernet11', 'Ethernet11']
        - name: L12
          id: 12
          mgmt_ip: 192.168.0.112/24
          uplink_switch_interfaces: ['Ethernet12', 'Ethernet12', 'Ethernet12', 'Ethernet12']
    - group: pod6
      bgp_as: 65107
      nodes:
        - name: L13
          id: 13
          mgmt_ip: 192.168.0.113/24
          uplink_switch_interfaces: ['Ethernet13', 'Ethernet13', 'Ethernet13', 'Ethernet13']
        - name: L14
          id: 14
          mgmt_ip: 192.168.0.114/24
          uplink_switch_interfaces: ['Ethernet14', 'Ethernet14', 'Ethernet14', 'Ethernet14']
    - group: pod7
      bgp_as: 65108
      nodes:
        - name: L15
          id: 15
          mgmt_ip: 192.168.0.115/24
          uplink_switch_interfaces: ['Ethernet15', 'Ethernet15', 'Ethernet15', 'Ethernet15']
        - name: L16
          id: 16
          mgmt_ip: 192.168.0.116/24
          uplink_switch_interfaces: ['Ethernet16', 'Ethernet16', 'Ethernet16', 'Ethernet16']
    - group: pod8
      bgp_as: 65109
      nodes:
        - name: L17
          id: 17
          mgmt_ip: 192.168.0.117/24
          uplink_switch_interfaces: ['Ethernet17', 'Ethernet17', 'Ethernet17', 'Ethernet17']
        - name: L18
          id: 18
          mgmt_ip: 192.168.0.118/24
          uplink_switch_interfaces: ['Ethernet18', 'Ethernet18', 'Ethernet18', 'Ethernet18']
    - group: pod9
      bgp_as: 65110
      nodes:
        - name: L19
          id: 19
          mgmt_ip: 192.168.0.119/24
          uplink_switch_interfaces: ['Ethernet19', 'Ethernet19', 'Ethernet19', 'Ethernet19']
        - name: L20
          id: 20
          mgmt_ip: 192.168.0.120/24
          uplink_switch_interfaces: ['Ethernet20', 'Ethernet20', 'Ethernet20', 'Ethernet20']

p2p_uplinks_mtu: 9214

l2leaf:
  defaults:
    platform: cEOS
    spanning_tree_mode: mstp
    uplink_interfaces: [ Ethernet11, Ethernet12 ]

  nodes:
    - name: L2L01
      id: 1
      mgmt_ip: 192.168.0.201/24
      uplink_switches: [ L01, L02 ]
      uplink_switch_interfaces: [ Ethernet11, Ethernet11 ]
    - name: L2L10
      id: 10
      mgmt_ip: 192.168.0.210/24
      uplink_switches: [ L09, L10 ]
      uplink_switch_interfaces: [ Ethernet12, Ethernet12 ]
